### PR TITLE
Added --prefix and --postfix assembler options

### PR DESCRIPTION
**Pull request by ajkhoury**
Also added proper documentation help urls, and an execution description that matches MASM's.

### CODE REVIEW

**Comment by Sibras** [comment]
Before this can be properly reviewed you need to fix the line endings of your commit. As you can see from the 'files changed' for this pull request you have caused every line of every touched file to be changed.
You can use something like Notepad++ to fix the line endings and then correct your commit so that it only shows the lines that have been modified and then update the pull request.

**Comment by ajkhoury** [comment]
Sorry for the mess.

**Comment by ajkhoury** [comment]
Lines endings should now be fixed, sorry about that. I ended up just changing core.eol globally lol.

**Comment by Sibras** [comment]
I fixed the issue with line endings in the repo which resulted in conflicts with this pull request.
So I applied the patch manually (with some minor changes).
thanks.

**Comment by Sibras** [comment]
FYI you might have to re-clone the repo to update the files with the new line ending normalisations. However the eol changes should remove the need to set core.eol globally and make submitting changes easier.
Let me know if you have any issues (or if i missed anything when manually applying the patch).

**Comment by ajkhoury** [comment]
Perfect, thanks :)

**Pull request closed without merging**
