### PR TITLE
Copy nasm.exe then delete it instead of moving it due to an issue on Windows 10.

### PR DESCRIPTION
**Pull request by ajkhoury**

### CODE REVIEW

**Comment by Sibras** [comment]
Your pull request has gotten a bit messed up (you may need to do a rebase -i followed by a push -f to correct your tree). But in the meantime i can review the "copy nasm ...." commit on its own.
So what is the issue that this commit fixes? I am also running Windows 10 and havent run into anything.

**Comment by ajkhoury** [comment]
The issue is when nasm.exe already exists in the VC install directory. What exactly is messed up? I had to merge because of a conflict with my changes.

**Comment by Sibras** [comment]
What I meant was that this pull request contains 5 different commits whereas for this kind of pull it should just contain the single commit for the mentioned change.

As for the mentioned change, the line before the move command should currently delete the existing nasm.exe. So whether it is a copy or a move there should not be an existing nasm.exe to cause issues anyway. The only time this should cause issues is when the delete command fails as it doesn't have admin rights to modify the VS install directory. In this case the move command failing is actually the expected outcome as the script will only work if run with admin privileges. So im not sure I understand what this fixes.

**Comment by ajkhoury** [comment]
It seems to only be a problem on Windows 10 with Visual Studio 2017. It's really strange. I'll gather some more information on whats happening for you, because I am running from an elevated command prompt, and there is really no reason move should be failing.

**Comment by Sibras** [comment]
I found the issue and applied a fix for it. The move command had some invalid options that was causing it to fail. Should be fixed in the repo now.

**Comment by ajkhoury** [comment]
Nice, thank you!

**Pull request closed without merging**
