### PR TITLE
added incremental build support

### PR DESCRIPTION
**Pull request by coelacanthus**

### CODE REVIEW

**Comment by Sibras** [comment]
What circumstances does this benefit i.e. what additional features does this add over existing functionality?

**Comment by coelacanthus** [comment]
This is a patch for [issue #13](https://github.com/ShiftMediaProject/VSNASM/issues/13).
Because **M**asm rebuild works fine, I tried to find differences between **m**asm.targets and **n**asm.targets.
And I found a gap and filled it for **n**asm.targets with tiny changes.

**Comment by Sibras** [comment]
The current targets file already has tlog output [https://github.com/ShiftMediaProject/VSNASM/blob/acfe9db73e0de4b9ad4d6c9dd7720784a6a670df/nasm.targets#L38](https://github.com/ShiftMediaProject/VSNASM/blob/acfe9db73e0de4b9ad4d6c9dd7720784a6a670df/nasm.targets#L38).

If there is an issue that this PR improves upon that the existing code does not then ensure that the existing tlog code is completely replaced by removing it and ensuring all test cases still work as desired.

**Comment by coelacanthus** [comment]
I removed the old tlog code and it still works fine with VS2019. I don't have older versions of VS and now getting older VS is required MSDN subscription, so I couldn't test for those. This PR needs help to be tested by anyone who uses older VS.

**Pull request merged**
